### ISSUE TITLE
Quest List TODO

### ISSUE THREAD

**Issue by pietro-lopes** [AllTheMods/Gravitas2#58]
# Textures
- [ ] Credits
- [ ] Gravitas 1 reference on root of the quest and inside chapter 1

# Outdated References
- [ ] Remove Blaze Map instructions
- [ ] Update Javelin tag to `tfc:javelins`
- [ ] Rework Kaolin/Graphite quests
- [ ] Update kelp and electron tags to single item
- [ ] Remove/Update references to:
  - [ ]  Ad Astra
  - [ ]  Immersive Engineering
  - [ ] TFC Casting with Channels
  - [ ] Thermal
  - [ ] Chemlib (GT Quests)

# Improvements
- [ ] Copper pickaxe shouldn't be mandatory, needs to be optional with Bronze
- [ ] Add links between quests like TFC -> GregTech, TFC -> Transportation, TFC -> Create
- [ ] Add GregTech Steam Age Quest line

# Quality of Life
- [ ] Use KubeJS to autocomplete some quest sequence based on certain achievements check points

**Comment by Eragonsaphria** [comment]
Gregtech bronze soft locked. I believe you can get around this by resmelting bronze into an ingot mld but the tag should just be any:bronze

**Comment by thevortex** [comment]
@Eragonsaphria 
> Gregtech bronze soft locked. I believe you can get around this by resmelting bronze into an ingot mld but the tag should just be any:bronze

stop derailing. make a new issue and stop posting unrelated stuff
